version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: rails_sandbox_db
    ports:
      - "3307:3306"
    env_file:
      - ./environments/db.env
    volumes:
      - mysql-db-data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rails_sandbox_api
    volumes:
      - bundle-install:/usr/local/bundle
      - .:/rails
    env_file:
      - ./environments/db.env
      - ./environments/api.env
    ports:
      - "3001:3001"
    links:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql-db-data:
  bundle-install:
