default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { '' } %>
  host: <%= ENV.fetch('MYSQL_HOST') { '127.0.0.1' } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_sandbox_development

test:
  <<: *default
  database: rails_sandbox_test

production:
  <<: *default
  database: rails_sandbox_production
  username: rails_sandbox
  password: <%= ENV['RAILS_SANDBOX_DATABASE_PASSWORD'] %>
